// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: embedding.proto

package embedding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"` // Allows for batch processing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEmbeddingRequest) Reset() {
	*x = TextEmbeddingRequest{}
	mi := &file_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEmbeddingRequest) ProtoMessage() {}

func (x *TextEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*TextEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *TextEmbeddingRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type ImageEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []string               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"` // Allows for batch processing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageEmbeddingRequest) Reset() {
	*x = ImageEmbeddingRequest{}
	mi := &file_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageEmbeddingRequest) ProtoMessage() {}

func (x *ImageEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*ImageEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *ImageEmbeddingRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*Vector              `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_embedding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{2}
}

func (x *EmbeddingResponse) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"` // The high-dimensional float array
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_embedding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{3}
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_embedding_proto protoreflect.FileDescriptor

const file_embedding_proto_rawDesc = "" +
	"\n" +
	"\x0fembedding.proto\x12\tembedding\",\n" +
	"\x14TextEmbeddingRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\"/\n" +
	"\x15ImageEmbeddingRequest\x12\x16\n" +
	"\x06images\x18\x01 \x03(\tR\x06images\"@\n" +
	"\x11EmbeddingResponse\x12+\n" +
	"\avectors\x18\x01 \x03(\v2\x11.embedding.VectorR\avectors\" \n" +
	"\x06Vector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values2\xa4\x01\n" +
	"\bEmbedder\x12J\n" +
	"\tEmbedText\x12\x1f.embedding.TextEmbeddingRequest\x1a\x1c.embedding.EmbeddingResponse\x12L\n" +
	"\n" +
	"EmbedImage\x12 .embedding.ImageEmbeddingRequest\x1a\x1c.embedding.EmbeddingResponseB-Z+services/vector-api/internal/stub/embeddingb\x06proto3"

var (
	file_embedding_proto_rawDescOnce sync.Once
	file_embedding_proto_rawDescData []byte
)

func file_embedding_proto_rawDescGZIP() []byte {
	file_embedding_proto_rawDescOnce.Do(func() {
		file_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embedding_proto_rawDesc), len(file_embedding_proto_rawDesc)))
	})
	return file_embedding_proto_rawDescData
}

var file_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_embedding_proto_goTypes = []any{
	(*TextEmbeddingRequest)(nil),  // 0: embedding.TextEmbeddingRequest
	(*ImageEmbeddingRequest)(nil), // 1: embedding.ImageEmbeddingRequest
	(*EmbeddingResponse)(nil),     // 2: embedding.EmbeddingResponse
	(*Vector)(nil),                // 3: embedding.Vector
}
var file_embedding_proto_depIdxs = []int32{
	3, // 0: embedding.EmbeddingResponse.vectors:type_name -> embedding.Vector
	0, // 1: embedding.Embedder.EmbedText:input_type -> embedding.TextEmbeddingRequest
	1, // 2: embedding.Embedder.EmbedImage:input_type -> embedding.ImageEmbeddingRequest
	2, // 3: embedding.Embedder.EmbedText:output_type -> embedding.EmbeddingResponse
	2, // 4: embedding.Embedder.EmbedImage:output_type -> embedding.EmbeddingResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_embedding_proto_init() }
func file_embedding_proto_init() {
	if File_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embedding_proto_rawDesc), len(file_embedding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embedding_proto_goTypes,
		DependencyIndexes: file_embedding_proto_depIdxs,
		MessageInfos:      file_embedding_proto_msgTypes,
	}.Build()
	File_embedding_proto = out.File
	file_embedding_proto_goTypes = nil
	file_embedding_proto_depIdxs = nil
}
